version: '3.8'

services:
  user_db:
    image: postgres:14
    container_name: user_db
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: ./social_network/user_service
    container_name: user_service
    environment:
      - DATABASE_URL=postgresql://user:password@user_db:5432/users_db
      - SECRET_KEY=your-secret-key-here-change-in-production
    depends_on:
      user_db:
        condition: service_healthy
    ports:
      - "8001:8001"

  api_gateway:
    build: ./social_network/api_gateway
    container_name: api_gateway
    environment:
      - USER_SERVICE_URL=http://user_service:8001
      - SECRET_KEY=your-secret-key-here-change-in-production
    depends_on:
      - user_service
    ports:
      - "8000:8000"

volumes:
  user_db_data: